### ISSUE TITLE
INFOGRAFIA DE LIBRERIAS 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/infografia-de-las-librerias-javiern-778#2]
![LIBRERIAS](https://user-images.githubusercontent.com/79878933/114665552-cead8980-9cc2-11eb-8713-69d2c638d7cf.jpg)

**Comment by Ferch0419** [comment]
Porcentaje obtenido: 20%   Calificado por Fernando Miguel López

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
